filebeat.inputs:
  - type: filestream
    id: honeypot-logs
    enabled: true
    paths:
      - /app/logs/*.log
    json.keys_under_root: false
    json.add_error_key: true

logging.level: debug
logging.selectors: ["*"]
# ILM must be enabled for data streams
setup.ilm.enabled: true

# Remove all template.name / pattern — Filebeat will use data stream templates
setup.template.enabled: true
setup.template.priority: 200

output.elasticsearch:
  hosts: ["https://10.0.0.135:9200"]
  username: "elastic"
  password: "<your-password>"
  ssl.verification_mode: none
  pipeline: "honeypot-pipeline"

# Use data stream routing
output.elasticsearch.indices:
  - index: "honeypot-logs"  
    pipeline: "honeypot-pipeline"
