filebeat.inputs:
  - type: filestream
    id: honeypot-logs
    enabled: true
    paths:
      - /app/logs/*.log
    json.keys_under_root: true
    json.overwrite_keys: true
    json.message_key: "message"
    multiline.pattern: '^{'
    multiline.negate: true
    multiline.match: after

processors:
  - timestamp:
      field: timestamp
      layouts:
        - '2006-01-02T15:04:05.000000Z07:00'

setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"

output.elasticsearch:
  hosts: ["https://localhost:9200"]
  index: "honeypot-logs-%{+yyyy.MM.dd}"
  pipeline: "honeypot-ecs-pipeline"
  username: "elastic"
  password: "<your-password>"
  ssl.verification_mode: "none"