filebeat.inputs:
  - type: filestream
    id: adv-int-ecs-logs
    enabled: true
    paths:
      - /app/logs/*.log
    json.keys_under_root: false  # Reverted to false
    json.add_error_key: true
    ignore_older: 0s

logging.level: debug
logging.selectors: ["*"]
# ILM must be enabled for data streams
setup.ilm.enabled: true
setup.template.name: "adv-intel-logs-template"
setup.template.pattern: "logs-adv_intel-*"

output.elasticsearch:
  hosts: ["https://10.0.0.135:9200"]
  data_stream:
    type: logs
    dataset: adv_intel
    namespace: default
  index: "logs-adv_intel-%{+yyyy.MM.dd}"
  pipeline: "adv-intel-ecs-enrich"
  username: "elastic"
  password: "changeme"
  ssl.verification_mode: none