filebeat.inputs:
  - type: filestream
    id: adv-int-ecs-logs
    enabled: true
    paths:
      - /app/logs/*.log
    json.keys_under_root: true
    json.overwrite_keys: true
    json.add_error_key: true
    ignore_older: 0s

setup.ilm.enabled: true
setup.template.enabled: true
logging.level: debug
logging.selectors: ["*"]
# ILM must be enabled for data streams
setup.ilm.enabled: true

# Remove all template.name / pattern — Filebeat will use data stream templates
setup.template.enabled: true
setup.template.name: "adv-intel-logs-template"
setup.template.pattern: "adv-intel-logs-*"

output.elasticsearch:
  hosts: ["https://localhost:9200"]
  index: "adv-intel-logs"
  pipeline: "adv-intel-ecs-enrich"
  username: "elastic"
  password: "changeme"
  ssl.verification_mode: none